apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: meryembarkallah21/youtube:latest
          ports:
            - containerPort: 4004  
---

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # You can use port 80 here for HTTP traffic
      targetPort: 4004  # This should match the port your Node.js applicatio
  type: NodePort
